# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workday_app', '0002_auto_20191012_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workday_app.Workday'),
        ),
    ]
